# Generated by Django 5.2 on 2025-05-06 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FarePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('pickup_lat', models.FloatField()),
                ('pickup_lon', models.FloatField()),
                ('dropoff_lat', models.FloatField()),
                ('dropoff_lon', models.FloatField()),
                ('distance', models.FloatField()),
                ('duration', models.IntegerField()),
                ('surge_multiplier', models.FloatField()),
                ('weather', models.CharField(max_length=50)),
                ('fare_inr', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
