# Generated by Django 5.2 on 2025-05-08 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickshift', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fareprediction',
            name='vehicle_type',
            field=models.CharField(choices=[('bike', 'Bike'), ('auto', 'Auto'), ('car', 'Car')], default='car', max_length=10),
            preserve_default=False,
        ),
    ]
